        // ********************* DEFECT ATTACKS *********************

        case CardId::ALL_FOR_ONE: {
            const int dmg = calculateCardDamage(c, t, up ? 14 : 10);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                int size = b.cards.discardPile.size();
                for (int i = size - 1; i >= 0; --i) {
                    if (b.cards.discardPile[i].costForTurn == 0 || b.cards.discardPile[i].cost == 0) {
                        if (b.cards.cardsInHand >= 10) break;
                        auto cardZero = b.cards.discardPile[i];
                        b.cards.removeFromDiscard(i);
                        b.cards.moveToHand(cardZero);
                    }
                }
            }) );
            break;
        }

        case CardId::BALL_LIGHTNING: {
            const int dmg = calculateCardDamage(c, t, up ? 10 : 7);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) { b.player.channelOrb(b, Orb::LIGHTNING); }) );
            break;
        }

        case CardId::BARRAGE: {
            const int dmg = calculateCardDamage(c, t, up ? 6 : 4);
            addToBot( Action([&](BattleContext &b) {
                int numOrbs = 0;
                for (int i=0; i<b.player.orbSlots; ++i) {
                    if (b.player.orbs[i] != Orb::EMPTY) numOrbs++;
                }
                for (int i=0; i<numOrbs; ++i) {
                    b.addToTop( Actions::AttackEnemy(t, dmg) );
                }
            }) );
            break;
        }

        case CardId::BEAM_CELL: {
            const int dmg = calculateCardDamage(c, t, up ? 4 : 3);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Actions::DebuffEnemy<MS::VULNERABLE>(t, up ? 2 : 1, false) );
            break;
        }

        case CardId::BLIZZARD: {
            addToBot( Action([&](BattleContext &b) {
                int d = b.player.frostOrbsChanneledThisCombat * (up ? 3 : 2);
                int baseDmg = b.calculateCardDamage(c, -1, d);
                b.addToTop( Actions::AttackAllEnemy(baseDmg) );
            }) );
            break;
        }

        case CardId::BRILLIANCE: {
            // NOT IMPLEMENTED (Custom mod card often mistakenly generated by get_defect_cards script)
            break;
        }

        case CardId::BULLSEYE: {
            const int dmg = calculateCardDamage(c, t, up ? 11 : 8);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Actions::DebuffEnemy<MS::LOCK_ON>(t, up ? 3 : 2, false) );
            break;
        }

        case CardId::CLAW: {
            const int dmg = calculateCardDamage(c, t, up ? 5 : 3);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                b.cards.clawDamage += 2;
            }) );
            break;
        }

        case CardId::COLD_SNAP: {
            const int dmg = calculateCardDamage(c, t, up ? 9 : 6);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) { b.player.channelOrb(b, Orb::FROST); }) );
            break;
        }

        case CardId::CORE_SURGE: {
            const int dmg = calculateCardDamage(c, t, up ? 15 : 11);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Actions::BuffPlayer<PS::ARTIFACT>(1) );
            break;
        }

        case CardId::DOOM_AND_GLOOM: {
            const int dmg = calculateCardDamage(c, -1, up ? 14 : 10);
            addToBot( Actions::AttackAllEnemy(dmg) );
            addToBot( Action([&](BattleContext &b) { b.player.channelOrb(b, Orb::DARK); }) );
            break;
        }

        case CardId::FTL: {
            const int dmg = calculateCardDamage(c, t, up ? 6 : 5);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                if (b.player.cardsPlayedThisTurn <= 3) { // This card included (but played count handled carefully)
                    // if it's 3rd card or less played
                    b.addToTop( Actions::DrawCards(1) );
                }
            }) );
            break;
        }

        case CardId::GO_FOR_THE_EYES: {
            const int dmg = calculateCardDamage(c, t, up ? 4 : 3);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                if (b.monsters.arr[t].isAttacking()) {
                    b.addToTop( Actions::DebuffEnemy<MS::WEAK>(t, up ? 2 : 1, false) );
                }
            }) );
            break;
        }

        case CardId::HYPERBEAM: {
            const int dmg = calculateCardDamage(c, -1, up ? 34 : 26);
            addToBot( Actions::AttackAllEnemy(dmg) );
            addToBot( Actions::DebuffPlayer<PS::FOCUS>(3) );
            break;
        }

        case CardId::MELTER: {
            addToBot( Action([&](BattleContext &b) {
                b.monsters.arr[t].block = 0; // Remove all block
            }) );
            const int dmg = calculateCardDamage(c, t, up ? 14 : 10);
            addToBot( Actions::AttackEnemy(t, dmg) );
            break;
        }

        case CardId::METEOR_STRIKE: {
            const int dmg = calculateCardDamage(c, t, up ? 30 : 24);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                for (int i=0; i<3; ++i) b.player.channelOrb(b, Orb::PLASMA);
            }) );
            break;
        }

        case CardId::REBOUND: {
            const int dmg = calculateCardDamage(c, t, up ? 12 : 9);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Actions::BuffPlayer<PS::REBOUND>(1) );
            break;
        }

        case CardId::RIP_AND_TEAR: {
            const int dmg = calculateCardDamage(c, t, up ? 9 : 7);
            addToBot( Actions::DamageRandomEnemy(dmg) );
            addToBot( Actions::DamageRandomEnemy(dmg) );
            break;
        }

        case CardId::SCRAPE: {
            const int dmg = calculateCardDamage(c, t, up ? 10 : 7);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                b.addToTop( Actions::DrawCards(4) ); /* Scrape discard logic omitted */
            }) );
            break;
        }

        case CardId::STREAMLINE: {
            const int dmg = calculateCardDamage(c, t, up ? 20 : 15);
            addToBot( Actions::AttackEnemy(t, dmg) );
            addToBot( Action([&](BattleContext &b) {
                for(int i=0; i<b.cards.cardsInHand; ++i) {
                    if (b.cards.hand[i].uniqueId == c.uniqueId) {
                        b.cards.hand[i].costForTurn = std::max(0, b.cards.hand[i].costForTurn - 1);
                        b.cards.hand[i].cost = std::max(0, b.cards.hand[i].cost - 1);
                    }
                }
            }) );
            break;
        }

        // CardId::STRIKE_BLUE is defined natively in STS lightspeed

        case CardId::SUNDER: {
            const int dmg = calculateCardDamage(c, t, up ? 32 : 24);
            addToBot( Action([&](BattleContext &b) {
                int hpBefore = b.monsters.arr[t].curHp;
                b.monsters.arr[t].attacked(b, dmg);
                if (hpBefore > 0 && b.monsters.arr[t].curHp <= 0) {
                    b.addToTop( Actions::GainEnergy(3) );
                }
            }) );
            break;
        }

        case CardId::SWEEPING_BEAM: {
            const int dmg = calculateCardDamage(c, -1, up ? 9 : 6);
            addToBot( Actions::AttackAllEnemy(dmg) );
            addToBot( Actions::DrawCards(1) );
            break;
        }

        case CardId::THUNDER_STRIKE: {
            addToBot( Action([&](BattleContext &b) {
                int d = b.player.lightningOrbsChanneledThisCombat;
                int baseDmg = b.calculateCardDamage(c, -1, up ? 9 : 7); // Base damage sent to RandomEnemy
                for (int i=0; i<d; ++i) {
                    b.addToTop( Actions::DamageRandomEnemy(baseDmg) );
                }
            }) );
            break;
        }
